unique_ids:
  assets:
    standard-page.html: X7M52JS6XA2R5PQOH7WPMBANUAVCCI7G
    theme.css: HU2FS4HCYBY2RNGPQOJLQ6UNPBYPTVTZ
  forms:
    Form1: H44G4ITBS3YJTHPLH2R6WYRCYTSFBXQG
  modules: {}
  scripts: {}
  server_modules: {}
